simplereading/translate/urls.py
from django.conf.urls import *
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
                url(r'^$', views.index, name='index'),
                url(r'^result/(?P<hard_text>[\w\W]*)/$', views.result, name='result'),
                url(r'^contribute/', views.contribute, name='contribute'),
                url(r'^add_simp/(?P<pk>\d+)/$', views.add_simp, name='add_simp'),
                url(r'^edit_simp/(?P<pk>\d+)/$', views.edit_simp, name='edit_simp'),
                url(r'^add_origin/', views.add_origin, name='add_origin'),
               
               ]

simplereading/translate/models.py
from django.db import models


class Original(models.Model):
    hard_text = models.TextField()
    
    def __str__(self):
        return self.hard_text

class Simple(models.Model):
    hard = models.ForeignKey(Original, on_delete=models.CASCADE)
    simple_text = models.TextField()

    def __str__(self):
        return self.simple_text

class Vote(models.Model):
    hard = models.ForeignKey(Original, on_delete=models.CASCADE)
    simple = models.ForeignKey(Simple, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)

class Simplify(models.Model):
    input = models.TextField()
    output = models.TextField()

class Comment(models.Model):
    history = models.ForeignKey(Simplify, on_delete=models.CASCADE)
    comment = models.TextField()
    
    def __str__(self):
        return self.comment

simplereading/translate/forms.py
from django import forms
from .models import Simple, Original, Vote, Simplify, Comment
from django.utils.safestring import mark_safe

class OriginForm(forms.ModelForm):
    hard_text = forms.CharField(widget=forms.Textarea(attrs={'rows':20, 'cols':80}), label='')
    class Meta:
        model = Original
        fields = ('hard_text',)

class TestForm(forms.Form):
     original_text = forms.CharField(widget=forms.Textarea(attrs={'rows':5, 'cols':60}), label='')

class SimpForm(forms.ModelForm):
    simple_text = forms.CharField(widget=forms.Textarea(attrs={'rows':20, 'cols':80}), label='')
    class Meta:
        model = Simple
        exclude = ('hard',)

class CommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={'rows':10, 'cols':60}), label='')
    class Meta:
        model = Comment
        exclude = ('history',)

class SimplifyForm(forms.ModelForm):
    input = forms.CharField(widget=forms.Textarea(attrs={'rows':20, 'cols':80}))
    output = forms.CharField(widget=forms.Textarea(attrs={'rows':20, 'cols':80}))
    class Meta:
        model = Simplify
        fields = ('input','output',)

class VoteForm(forms.ModelForm):
    votes = forms.IntegerField(required=True)
    class Meta:
        model = Vote
        fields = ('votes',)

simplereading/translate/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Simple, Original, Vote, Simplify, Comment
from .forms import OriginForm, SimpForm, TestForm, CommentForm, SimplifyForm, VoteForm
from django.core.urlresolvers import reverse
import functions, utils


def index(request):
    if 'original_text' in request.GET and request.GET["original_text"]:
        hard_text = request.GET.get("original_text")
        return redirect('result', hard_text)
    else:
        form = TestForm()
        return render(request, 'index.html', {'form' : form})


def result(request, hard_text):
    form = TestForm(initial={'original_text': hard_text})
    formc = CommentForm()
    simple, process = utils.simplify(hard_text)
    if 'original_text' in request.GET and request.GET["original_text"]:
        hard_text = request.GET.get("original_text")
        return redirect('result', hard_text)
    elif request.method == "POST":
        if 'comment' in request.POST:
            comment = request.POST.get("comment")
            comment_form = CommentForm(request.POST)
            history_form = SimplifyForm()
            if comment_form.is_valid():
                try:
                    history = Simplify.objects.get(input=hard_text, output=simple)
                except Simplify.DoesNotExist:
                    history =history_form.save(commit=False)
                    history.input = hard_text
                    history.output=simple
                    history.save()
                    com = comment_form.save(commit=False)
                    com.history = history
                    com.comment = comment
                    com.save()
                    comments = Comment.objects.filter(history=history.id)
                    return render(request, 'result.html', {'simple': simple, 'form' : form, 'formc':formc, 'com':comments,'process':process})
            else:
                try:
                    history = Simplify.objects.get(input=hard_text, output=simple)
                except Simplify.DoesNotExist:
                    return render(request, 'result.html', {'simple': simple, 'form' : form, 'formc':formc,'process':process})
                comments = Comment.objects.filter(history=history.id)
                return render(request, 'result.html', {'simple': simple, 'form' : form, 'formc':formc, 'com':comments,'process':process})
    else:
        try:
            history = Simplify.objects.get(input=hard_text, output=simple)
        except Simplify.DoesNotExist:
            return render(request, 'result.html', {'simple': simple, 'form' : form, 'formc':formc,'process':process})
        comments = Comment.objects.filter(history=history.id)
        return render(request, 'result.html', {'simple': simple, 'form' : form, 'formc':formc, 'com':comments,'process':process})

def contribute(request):
    origins = Original.objects.all()
    return render(request, 'contribute.html', {'origins' : origins })


def add_simp(request, pk):
    orig = Original.objects.get(pk=pk)
    form = SimpForm()
    results = Simple.objects.filter(hard=pk)
    if request.method =="POST":
        if 'simple_text' in request.POST and request.POST["simple_text"]:
            simple_text = request.POST.get("simple_text")
            save_form = SimpForm(request.POST)
            if save_form.is_valid():
                simp = save_form.save(commit=False)
                simp.simple_text = simple_text
                simp.hard = orig
                simp.save()
                return render(request, 'add_simp.html', {'results': results, 'orig' : orig, 'form': form })
        elif 'votes' in request.POST and request.POST["votes"]:
            votes = request.POST.getlist("votes")
            for vote in votes:
                vote_form = VoteForm()
                simple=Simple.objects.get(hard=orig, simple_text=vote)
                try:
                    v = Vote.objects.get(hard=orig, simple=simple)
                    v.votes += 1
                    v.save()
                except Vote.DoesNotExist:
                    v = vote_form.save(commit=False)
                    v.hard=orig
                    v.simple=simple
                    v.votes=1
                    v.save()
            vote_result = Vote.objects.get(hard=orig, simple=simple)
            return render(request, 'add_simp.html', {'results': results, 'orig' : orig, 'form': form})
        else:
            return render(request, 'add_simp.html', {'results': results, 'orig' : orig, 'form': form})
    else:
        return render(request, 'add_simp.html', {'results': results, 'orig' : orig, 'form': form})


def edit_simp(request, pk):
    simp = Simple.objects.get(pk=pk)
    form = SimpForm(initial={'simple_text': simp.simple_text})
    new_simple_text = request.POST.get("simple_text")
    if request.method =="POST":
        simp.simple_text = new_simple_text
        simp.save()
        return redirect('add_simp', simp.hard.id )
    else:
        return render(request, 'edit_simp.html', {'form' : form})

def add_origin(request):
    hard_text = request.POST.get("hard_text")
    if request.method =="POST":
        save_form = OriginForm(request.POST)
        if save_form.is_valid():
            orig = save_form.save(commit=False)
            orig.hard_text = hard_text
            orig.save()
            origins = Original.objects.all()
        return redirect('contribute')
    else:
        form = OriginForm()
        return render(request, 'add_origin.html', { 'form':form })

simplereading/templates/add_origin.html
{% extends 'base.html' %}
{% block content %}
{% csrf_token %}
<br/>

<form method="POST" name="add original text" >{% csrf_token %}
    <label for="id_hard_text"><h1 id="h1_contribute">Please input original text:</h1></label><br/><br/><br/>
    {{ form.as_p }}<br/>
    <input type="submit" value="submit"  />
</form><br />

{% endblock content %}

simplereading/templates/add_simp.html
{% extends 'base.html' %} 
{% block content %} <br/>
<h1 id="h1_contribute">Original Text:</h1><br/><br/>
<h2>{{ orig.hard_text }}</h2><br/>
<form method="POST" >{% csrf_token %}
    <label for="id_simple_text"><h2 id="h3_color">Simplify it:</h2></label>
    {{ form.as_p }}<br/>
    <input type="submit" value="submit"  />
</form><br /><HR/>
{% if results %}


<form name="vote for results" method="POST" >{% csrf_token %}
    <label for="vote"><h2 id="h3_color">Other simplified version:</h2></label>
    {% for result in results %}
    <h3><input type="checkbox" value={{ result.simple_text }} name="votes" id="vote">  {{ result.simple_text }}   </input><a href="{% url 'edit_simp' pk=result.id %}">edit</a></h3>
    {% endfor %}
    <br/>
    <input type="submit" value="Vote" />
</form>
{% endif %}
<br/>
{% endblock content %}

simplereading/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<title>Text Simplifier</title>
<link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css" />
</head>
<body >
<div id="default">
  <header id="head_div">
    <img class="float_left" alt="Simplifier" src="{% static 'images/simplifier.jpg' %}" height="201px">
    <h1 id="project_title"  class="float_left" > Simplifier </h1>
    </header>
  <nav id="nav_div">
    <ul id="nav_list">
      <li><a href="{% url 'index' %}" colour="white">Simplify </a></li>
      <li><a href="{% url 'contribute' %}">Contribute </a></li>
      </ul>
    </nav>
  <div id="main_container">
    
     
     {% block content %}
     {% endblock %}
	<footer id="footer_div"> T Wang Team @ CS682-3, UMB | &copy;  Copyright 2016 | All rights Reserved
	  <br>Team members: T Wang, N Lu, YH Luo, C Fakhry, X Ding
	  </footer>
  </div>
</div>
</body>
</html>

simplereading/templates/contribute.html
{% extends 'base.html' %} 
{% block content %} 
{% csrf_token %}
<br/>
<h1 id="h1_title" style="border-style: solid">In this page, you can simplify original text choosed from below. Or you can input
    original texts and let other users simplify it. </h1>
<br/><HR/><br/>

<h2>  You can add original sentence here: <a href="{% url 'add_origin' %}">add new original sentence</a></h2><br/>

<HR/><br/>

{% if origins %}
<h1 id="h1_contribute">Choose original text from below and simplify it:</h1><br/>
<h2>Original Text:</h2>
{% for origin in origins %}
<ul>
    <li><a href="{% url 'add_simp' pk=origin.id %}">{{ origin.hard_text }}</a></li>
</ul>
{% endfor %}
{% endif %}<br/><br/><br/>
{% endblock content %}

simplereading/templates/edit_simp.html
{% extends 'base.html' %} 
{% block content %} 
{% csrf_token %}
<br/>

<form method="POST" name="edit simplified text" >{% csrf_token %}
   <label> <h1 id="h1_contribute">Edit this simplified sentence:</h1></label><br/>
    <br/><br/>
    {{ form.as_p }}<br/>
    <input type="submit" value="submit"  />
</form><br />
{% endblock content %}

simplereading/templates/index.html

{% extends 'base.html' %}
{% block content %}
<h1 id="h1_title">Intend for people to write/understand texts in a simple way </h1><br/><br/><br/><br/>
<table id="h3_color" >
<form class="search-form" method="GET" name="input text you want to simplify">{% csrf_token %}
    
    <tr>
        <td><label for="id_original_text"><p>  Please inpute original text here:<input type="submit" style="float: right" value="Simplify"  /></p></label>{{ form.as_p }}</td>
        <td><label for="text_area"><p>Simplified:</p></label><textarea rows="5" cols="60" id="text_area"></textarea></td>
    </tr>
</form>
</table>
<br/><br/><br/><br/><br/><br/><br/><br/>
{% endblock content %}

simplereading/templates/result.html
{% extends 'base.html' %}
{% block content %}
<h1 id="h1_title">Intend for people to write/understand texts in a simple way </h1><br/>
<table  >
<form class="search-form" method="GET" name="input text you want to simplify">{% csrf_token %}
    
    <tr>
        <td><label for="id_original_text"><p>Please inpute original text here:<input type="submit" value="Simplify" style="float: right" ></p></label></td>
        
        <td><label for="simplified_text"><p>Simplified:</p></label>
        </td>
    </tr>
    <tr>
        <td>{{ form.as_p }}</td>
        <td><textarea rows="5" cols="60" wrap="hard" readonly="yes" name="text after simplified" id="simplified_text">{{ simple }}
        </textarea></td>
    </tr>
</form>
</table>
</br>
<h2>Process:</h2>
<p style="border-style:dashed">{{ process }}</p><br/><br/>
<form method="POST" >{% csrf_token %}
    <label for="id_comment"><p>    Leave a comment:</p></label>{{ formc.as_p }}<br />
       <input type="submit" value="submit"  />
</form><br/><br/>
{% if com %}
<h2>Comments:</h2><br/>
{% for comment in com %}<hr/>
<p>{{ comment.comment }}</p><br/>
{% endfor %}
{% endif %}
</br>
{% endblock content %}